In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pandas as pd
import math
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

%matplotlib inline

In [ ]:


# read data from the Excel file
data = pd.read_csv('HIGGS_train.csv')

# Set the column names
column_names = ['class label', 'lepton pT', 'lepton eta', 'lepton phi', 'missing energy magnitude', 
                'missing energy phi', 'jet 1 pt', 'jet 1 eta', 'jet 1 phi', 'jet 1 b-tag', 
                'jet 2 pt', 'jet 2 eta', 'jet 2 phi', 'jet 2 b-tag', 'jet 3 pt', 'jet 3 eta', 
                'jet 3 phi', 'jet 3 b-tag', 'jet 4 pt', 'jet 4 eta', 'jet 4 phi', 'jet 4 b-tag', 
                'm jj', 'm jjj', 'm lv', 'm jlv', 'm bb', 'm wbb', 'm wwbb']

data.columns = column_names

# Split data into features and target
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values

data

<ipython-input-79-193328a779fc>:2: DtypeWarning: Columns (8,21) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('HIGGS_train.csv')

,class label,lepton pT,lepton eta,lepton phi,missing energy magnitude,missing energy phi,jet 1 pt,jet 1 eta,jet 1 phi,jet 1 b-tag,...,jet 4 eta,jet 4 phi,jet 4 b-tag,m jj,m jjj,m lv,m jlv,m bb,m wbb,m wwbb
0,1.0,0.908,0.329,0.35900,1.500,-0.313,1.100,-0.558,-1.59,2.17,...,-1.140,-0.000819,0.0,0.302,0.833,0.986,0.978,0.780,0.992,0.798
1,1.0,0.799,1.470,-1.64000,0.454,0.426,1.100,1.280,1.38,0.00,...,1.130,0.900000,0.0,0.910,1.110,0.986,0.951,0.803,0.866,0.780
2,0.0,1.340,-0.877,0.93600,1.990,0.882,1.790,-1.650,-0.942,0.00,...,-0.678,-1.360000,0.0,0.947,1.030,0.999,0.728,0.869,1.030,0.958
3,1.0,1.110,0.321,1.52000,0.883,-1.210,0.681,-1.070,-0.922,0.00,...,-0.374,0.113000,0.0,0.756,1.360,0.987,0.838,1.130,0.872,0.808
4,0.0,1.600,-0.608,0.00707,1.820,-0.112,0.848,-0.566,1.58,2.17,...,-0.654,-1.270000,3.1,0.824,0.938,0.972,0.789,0.431,0.961,0.958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599994,0.0,0.680,0.223,-0.75700,0.418,-0.323,0.471,-0.394,0.103,0.00,...,-2.460,1.460000,0.0,0.823,1.040,0.985,0.868,0.258,0.776,0.712
599995,1.0,1.610,-1.620,0.21200,0.716,-0.906,0.553,-0.908,-1.56,2.17,...,0.538,-0.490000,3.1,0.810,0.643,1.260,1.020,0.626,0.773,0.701
599996,1.0,1.070,0.364,0.34400,0.617,-1.430,0.675,0.159,0.0789,0.00,...,0.978,1.150000,3.1,0.973,0.974,1.130,0.969,0.852,0.908,0.789
599997,1.0,1.180,-0.173,-1.46000,0.735,-0.753,1.020,-0.838,1.23,0.00,...,0.107,0.622000,0.0,0.812,1.240,0.986,0.694,0.745,0.741,0.728
599998,0.0,0.771,-0.133,-1.02000,1.790,-1.650,0.779,0.487,0.19,2.17,...,-0.314,0.667000,0.0,0.829,0.839,0.984,1.340,0.510,1.040,0.905

In [ ]:
data.isnull()

,class label,lepton pT,lepton eta,lepton phi,missing energy magnitude,missing energy phi,jet 1 pt,jet 1 eta,jet 1 phi,jet 1 b-tag,...,jet 4 eta,jet 4 phi,jet 4 b-tag,m jj,m jjj,m lv,m jlv,m bb,m wbb,m wwbb
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599994,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
599995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
599996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
599997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
599998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
n=[]
per=[]
for col in data.columns:
    n_miss = data[col].isnull().sum()
    n+=[n_miss]
    perc = n_miss / data.shape[0] * 100
    per+=[perc]
    print('> %s, Missing: %d (%.1f%%)' % (col, n_miss, perc))


d=pd.DataFrame({'features':data.columns,'number of missing data':n,'percebtage of missing data':per})

> class label, Missing: 0 (0.0%)
> lepton pT, Missing: 0 (0.0%)
> lepton eta, Missing: 0 (0.0%)
> lepton phi, Missing: 0 (0.0%)
> missing energy magnitude, Missing: 0 (0.0%)
> missing energy phi, Missing: 0 (0.0%)
> jet 1 pt, Missing: 0 (0.0%)
> jet 1 eta, Missing: 0 (0.0%)
> jet 1 phi, Missing: 0 (0.0%)
> jet 1 b-tag, Missing: 0 (0.0%)
> jet 2 pt, Missing: 0 (0.0%)
> jet 2 eta, Missing: 0 (0.0%)
> jet 2 phi, Missing: 0 (0.0%)
> jet 2 b-tag, Missing: 0 (0.0%)
> jet 3 pt, Missing: 0 (0.0%)
> jet 3 eta, Missing: 0 (0.0%)
> jet 3 phi, Missing: 0 (0.0%)
> jet 3 b-tag, Missing: 1 (0.0%)
> jet 4 pt, Missing: 0 (0.0%)
> jet 4 eta, Missing: 0 (0.0%)
> jet 4 phi, Missing: 0 (0.0%)
> jet 4 b-tag, Missing: 0 (0.0%)
> m jj, Missing: 0 (0.0%)
> m jjj, Missing: 0 (0.0%)
> m lv, Missing: 0 (0.0%)
> m jlv, Missing: 0 (0.0%)
> m bb, Missing: 0 (0.0%)
> m wbb, Missing: 0 (0.0%)
> m wwbb, Missing: 0 (0.0%)

In [ ]:
from numpy import NAN
n=[]
per=[]
# remove NAs values:
data=data.dropna()
for col in data.columns:
    n_miss = data[col].isnull().sum()
    n+=[n_miss]
    perc = n_miss / data.shape[0] * 100
    per+=[perc]
    print('> %s, Missing: %d (%.1f%%)' % (col, n_miss, perc))


d=pd.DataFrame({'features':data.columns,'number of missing data':n,'percebtage of missing data':per})
d

> class label, Missing: 0 (0.0%)
> lepton pT, Missing: 0 (0.0%)
> lepton eta, Missing: 0 (0.0%)
> lepton phi, Missing: 0 (0.0%)
> missing energy magnitude, Missing: 0 (0.0%)
> missing energy phi, Missing: 0 (0.0%)
> jet 1 pt, Missing: 0 (0.0%)
> jet 1 eta, Missing: 0 (0.0%)
> jet 1 phi, Missing: 0 (0.0%)
> jet 1 b-tag, Missing: 0 (0.0%)
> jet 2 pt, Missing: 0 (0.0%)
> jet 2 eta, Missing: 0 (0.0%)
> jet 2 phi, Missing: 0 (0.0%)
> jet 2 b-tag, Missing: 0 (0.0%)
> jet 3 pt, Missing: 0 (0.0%)
> jet 3 eta, Missing: 0 (0.0%)
> jet 3 phi, Missing: 0 (0.0%)
> jet 3 b-tag, Missing: 0 (0.0%)
> jet 4 pt, Missing: 0 (0.0%)
> jet 4 eta, Missing: 0 (0.0%)
> jet 4 phi, Missing: 0 (0.0%)
> jet 4 b-tag, Missing: 0 (0.0%)
> m jj, Missing: 0 (0.0%)
> m jjj, Missing: 0 (0.0%)
> m lv, Missing: 0 (0.0%)
> m jlv, Missing: 0 (0.0%)
> m bb, Missing: 0 (0.0%)
> m wbb, Missing: 0 (0.0%)
> m wwbb, Missing: 0 (0.0%)

,features,number of missing data,percebtage of missing data
0,class label,0,0.0
1,lepton pT,0,0.0
2,lepton eta,0,0.0
3,lepton phi,0,0.0
4,missing energy magnitude,0,0.0
5,missing energy phi,0,0.0
6,jet 1 pt,0,0.0
7,jet 1 eta,0,0.0
8,jet 1 phi,0,0.0
9,jet 1 b-tag,0,0.0
10,jet 2 pt,0,0.0
11,jet 2 eta,0,0.0
12,jet 2 phi,0,0.0
13,jet 2 b-tag,0,0.0
14,jet 3 pt,0,0.0
15,jet 3 eta,0,0.0
16,jet 3 phi,0,0.0
17,jet 3 b-tag,0,0.0
18,jet 4 pt,0,0.0
19,jet 4 eta,0,0.0
20,jet 4 phi,0,0.0
21,jet 4 b-tag,0,0.0
22,m jj,0,0.0
23,m jjj,0,0.0
24,m lv,0,0.0
25,m jlv,0,0.0
26,m bb,0,0.0
27,m wbb,0,0.0
28,m wwbb,0,0.0

In [ ]:
np.shape(data)

(599998, 29)

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pandas as pd
import math
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

%matplotlib inline

In [ ]:


# read data from the Excel file
data = pd.read_csv('HIGGS_train.csv')

# Set the column names
column_names = ['class label', 'lepton pT', 'lepton eta', 'lepton phi', 'missing energy magnitude', 
                'missing energy phi', 'jet 1 pt', 'jet 1 eta', 'jet 1 phi', 'jet 1 b-tag', 
                'jet 2 pt', 'jet 2 eta', 'jet 2 phi', 'jet 2 b-tag', 'jet 3 pt', 'jet 3 eta', 
                'jet 3 phi', 'jet 3 b-tag', 'jet 4 pt', 'jet 4 eta', 'jet 4 phi', 'jet 4 b-tag', 
                'm jj', 'm jjj', 'm lv', 'm jlv', 'm bb', 'm wbb', 'm wwbb']

data.columns = column_names

# Split data into features and target
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values

data

,class label,lepton pT,lepton eta,lepton phi,missing energy magnitude,missing energy phi,jet 1 pt,jet 1 eta,jet 1 phi,jet 1 b-tag,...,jet 4 eta,jet 4 phi,jet 4 b-tag,m jj,m jjj,m lv,m jlv,m bb,m wbb,m wwbb
0,1.0,0.908,0.329,0.35900,1.500,-0.313,1.100,-0.558,-1.590,2.17,...,-1.140,-0.000819,0.00,0.302,0.833,0.986,0.978,0.780,0.992,0.798
1,1.0,0.799,1.470,-1.64000,0.454,0.426,1.100,1.280,1.380,0.00,...,1.130,0.900000,0.00,0.910,1.110,0.986,0.951,0.803,0.866,0.780
2,0.0,1.340,-0.877,0.93600,1.990,0.882,1.790,-1.650,-0.942,0.00,...,-0.678,-1.360000,0.00,0.947,1.030,0.999,0.728,0.869,1.030,0.958
3,1.0,1.110,0.321,1.52000,0.883,-1.210,0.681,-1.070,-0.922,0.00,...,-0.374,0.113000,0.00,0.756,1.360,0.987,0.838,1.130,0.872,0.808
4,0.0,1.600,-0.608,0.00707,1.820,-0.112,0.848,-0.566,1.580,2.17,...,-0.654,-1.270000,3.10,0.824,0.938,0.972,0.789,0.431,0.961,0.958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141108,0.0,1.010,-1.780,-0.26600,0.729,0.994,0.688,-0.957,-1.020,0.00,...,0.861,-0.053000,1.55,0.860,0.857,1.080,0.814,0.433,0.726,0.724
141109,1.0,0.501,-0.227,-1.05000,1.640,0.156,1.630,-1.540,1.470,0.00,...,-0.433,0.743000,3.10,1.140,0.818,1.110,0.738,0.713,0.772,0.754
141110,0.0,0.731,-1.350,-0.44400,0.171,-1.170,0.752,-1.120,-1.640,2.17,...,-1.560,0.917000,0.00,0.715,1.120,0.999,0.840,0.725,1.410,1.180
141111,0.0,1.110,0.295,-0.59300,0.736,0.543,1.160,1.230,-1.640,2.17,...,1.940,-1.180000,0.00,0.534,0.795,1.070,0.906,1.580,1.040,0.852
141112,0.0,0.535,1.260,1.35000,0.815,-0.565,0.871,-0.548,0.373,0.00,...,-0.416,1.580000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
output=[]
for col in data.columns:
    n_miss = data[col].isnull().sum()
    perc = n_miss / data.shape[0] * 100
    output+=[perc]
    print('> %s, Missing: %d (%.1f%%)' % (col, n_miss, perc))

> class label, Missing: 0 (0.0%)
> lepton pT, Missing: 0 (0.0%)
> lepton eta, Missing: 0 (0.0%)
> lepton phi, Missing: 0 (0.0%)
> missing energy magnitude, Missing: 0 (0.0%)
> missing energy phi, Missing: 0 (0.0%)
> jet 1 pt, Missing: 0 (0.0%)
> jet 1 eta, Missing: 0 (0.0%)
> jet 1 phi, Missing: 0 (0.0%)
> jet 1 b-tag, Missing: 0 (0.0%)
> jet 2 pt, Missing: 0 (0.0%)
> jet 2 eta, Missing: 0 (0.0%)
> jet 2 phi, Missing: 0 (0.0%)
> jet 2 b-tag, Missing: 0 (0.0%)
> jet 3 pt, Missing: 0 (0.0%)
> jet 3 eta, Missing: 0 (0.0%)
> jet 3 phi, Missing: 0 (0.0%)
> jet 3 b-tag, Missing: 0 (0.0%)
> jet 4 pt, Missing: 0 (0.0%)
> jet 4 eta, Missing: 0 (0.0%)
> jet 4 phi, Missing: 0 (0.0%)
> jet 4 b-tag, Missing: 1 (0.0%)
> m jj, Missing: 1 (0.0%)
> m jjj, Missing: 1 (0.0%)
> m lv, Missing: 1 (0.0%)
> m jlv, Missing: 1 (0.0%)
> m bb, Missing: 1 (0.0%)
> m wbb, Missing: 1 (0.0%)
> m wwbb, Missing: 1 (0.0%)

In [ ]:
from numpy import NAN
# remove NAs values:
data=data.dropna()
for col in data.columns:
    n_miss = data[col].isnull().sum()
    perc = n_miss / data.shape[0] * 100
    print('> %s, Missing: %d (%.1f%%)' % (col, n_miss, perc))

> class label, Missing: 0 (0.0%)
> lepton pT, Missing: 0 (0.0%)
> lepton eta, Missing: 0 (0.0%)
> lepton phi, Missing: 0 (0.0%)
> missing energy magnitude, Missing: 0 (0.0%)
> missing energy phi, Missing: 0 (0.0%)
> jet 1 pt, Missing: 0 (0.0%)
> jet 1 eta, Missing: 0 (0.0%)
> jet 1 phi, Missing: 0 (0.0%)
> jet 1 b-tag, Missing: 0 (0.0%)
> jet 2 pt, Missing: 0 (0.0%)
> jet 2 eta, Missing: 0 (0.0%)
> jet 2 phi, Missing: 0 (0.0%)
> jet 2 b-tag, Missing: 0 (0.0%)
> jet 3 pt, Missing: 0 (0.0%)
> jet 3 eta, Missing: 0 (0.0%)
> jet 3 phi, Missing: 0 (0.0%)
> jet 3 b-tag, Missing: 0 (0.0%)
> jet 4 pt, Missing: 0 (0.0%)
> jet 4 eta, Missing: 0 (0.0%)
> jet 4 phi, Missing: 0 (0.0%)
> jet 4 b-tag, Missing: 0 (0.0%)
> m jj, Missing: 0 (0.0%)
> m jjj, Missing: 0 (0.0%)
> m lv, Missing: 0 (0.0%)
> m jlv, Missing: 0 (0.0%)
> m bb, Missing: 0 (0.0%)
> m wbb, Missing: 0 (0.0%)
> m wwbb, Missing: 0 (0.0%)

In [ ]:
# i will now remove all the data that cannot be converted into floats so that we can start implementing:

# convert the values in a column to numeric format
for i in data.columns:

  data[i] = pd.to_numeric(data[i], errors='coerce') # errors will convert non convertable data to NAN

# drop rows with NaN values
data.dropna(inplace=True)

<ipython-input-85-e0262c210070>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[i] = pd.to_numeric(data[i], errors='coerce') # errors will convert non convertable data to NAN
<ipython-input-85-e0262c210070>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [ ]:
np.shape(data)

(599995, 29)

In [ ]:
#xgboost:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:,0],test_size=0.2,random_state = 7651)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



xgb_model = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=6,
    min_child_weight=1,
    gamma=1,
    alpha=1.5,
    reg_lambda=1.0,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    n_estimators=100
)

# train the model on the training data
xgb_model.fit(X_train, y_train)
model_predict=xgb_model.predict(X_test)
model_predict_train=xgb_model.predict(X_train)
print('training accuracy of model is:',accuracy_score(y_train,model_predict_train))
print('testing accuracy of model is:',accuracy_score(y_test,model_predict))

training accuracy of model is: 0.7528545739620335
testing accuracy of model is: 0.7266413917726677

In [ ]:
#xgboost:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:,0],test_size=0.2,random_state = 7651)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



xgb_model = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=6,
    min_child_weight=1,
    gamma=1,
    alpha=1.5,
    reg_lambda=2.0,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    n_estimators=100
)

# train the model on the training data
xgb_model.fit(X_train, y_train)
model_predict=xgb_model.predict(X_test)
model_predict_train=xgb_model.predict(X_train)
print('training accuracy of model is:',accuracy_score(y_train,model_predict_train))
print('testing accuracy of model is:',accuracy_score(y_test,model_predict))

training accuracy of model is: 0.7525799679331024
testing accuracy of model is: 0.7248697870531127

In [ ]:
#xgboost:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:,0],test_size=0.2,random_state = 7651)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



xgb_model = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=6,
    min_child_weight=1,
    gamma=1,
    alpha=1.5,
    reg_lambda=2.5,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    n_estimators=100
)

# train the model on the training data
xgb_model.fit(X_train, y_train)
model_predict=xgb_model.predict(X_test)
model_predict_train=xgb_model.predict(X_train)
print('training accuracy of model is:',accuracy_score(y_train,model_predict_train))
print('testing accuracy of model is:',accuracy_score(y_test,model_predict))

training accuracy of model is: 0.7523319366811647
testing accuracy of model is: 0.7255075647521525

In [ ]:
#xgboost:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:,0],test_size=0.2,random_state = 7651)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



xgb_model = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=6,
    min_child_weight=1,
    gamma=1,
    alpha=1.5,
    reg_lambda=4,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    n_estimators=100
)

# train the model on the training data
xgb_model.fit(X_train, y_train)
model_predict=xgb_model.predict(X_test)
model_predict_train=xgb_model.predict(X_train)
print('training accuracy of model is:',accuracy_score(y_train,model_predict_train))
print('testing accuracy of model is:',accuracy_score(y_test,model_predict))

training accuracy of model is: 0.7509234735005182
testing accuracy of model is: 0.7269602806221875

In [ ]:
#xgboost:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:,0],test_size=0.2,random_state = 7651)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



xgb_model = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=6,
    min_child_weight=1,
    gamma=1,
    alpha=1.5,
    reg_lambda=5,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    n_estimators=100
)

# train the model on the training data
xgb_model.fit(X_train, y_train)
model_predict=xgb_model.predict(X_test)
model_predict_train=xgb_model.predict(X_train)
print('training accuracy of model is:',accuracy_score(y_train,model_predict_train))
print('testing accuracy of model is:',accuracy_score(y_test,model_predict))

training accuracy of model is: 0.7517384333283137
testing accuracy of model is: 0.7262516387343656

In [ ]:
#xgboost:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:,0],test_size=0.2,random_state = 7651)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



xgb_model = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=6,
    min_child_weight=1,
    gamma=1,
    alpha=1.5,
    reg_lambda=4.5,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    n_estimators=100
)

# train the model on the training data
xgb_model.fit(X_train, y_train)
model_predict=xgb_model.predict(X_test)
model_predict_train=xgb_model.predict(X_train)
print('training accuracy of model is:',accuracy_score(y_train,model_predict_train))
print('testing accuracy of model is:',accuracy_score(y_test,model_predict))

training accuracy of model is: 0.7517118585513203
testing accuracy of model is: 0.7255429968465436

In [ ]:


X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:,0],test_size=0.2,random_state = 7651)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


#xgboost:

xgb_model = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=5,
    min_child_weight=3,
    gamma=.8,
    alpha=0.1,
    reg_lambda=3.0,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    n_estimators=1000,
    scale_pos_weight=1
)

# train the model on the training data
xgb_model.fit(X_train, y_train)
model_predict=xgb_model.predict(X_test)
model_predict_train=xgb_model.predict(X_train)
print('training accuracy of model is:',accuracy_score(y_train,model_predict_train))
print('testing accuracy of model is:',accuracy_score(y_test,model_predict))

training accuracy of model is: 0.7703876698972492
testing accuracy of model is: 0.7407478395653297

In [ ]:


X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:,0],test_size=0.2,random_state = 7651)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


#xgboost:

xgb_model = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=5,
    min_child_weight=3,
    gamma=.8,
    alpha=0.1,
    reg_lambda=3.0,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    n_estimators=1500,
    scale_pos_weight=1
)

# train the model on the training data
xgb_model.fit(X_train, y_train)
model_predict=xgb_model.predict(X_test)
model_predict_train=xgb_model.predict(X_train)
print('training accuracy of model is:',accuracy_score(y_train,model_predict_train))
print('testing accuracy of model is:',accuracy_score(y_test,model_predict))

training accuracy of model is: 0.7837565313044276
testing accuracy of model is: 0.7415561796348303

In [ ]:
np.shape(data)

(599999, 29)

In [ ]:


X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:,0],test_size=0.2,random_state = 7651)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


#xgboost:

xgb_model = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=5,
    min_child_weight=3,
    gamma=.8,
    alpha=0.1,
    reg_lambda=3.0,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    n_estimators=5000,
    scale_pos_weight=1
)

# train the model on the training data
xgb_model.fit(X_train, y_train)
model_predict=xgb_model.predict(X_test)
model_predict_train=xgb_model.predict(X_train)
print('training accuracy of model is:',accuracy_score(y_train,model_predict_train))
print('testing accuracy of model is:',accuracy_score(y_test,model_predict))

training accuracy of model is: 0.8526175218126818
testing accuracy of model is: 0.7409978416486804